---
- name: setup vscode
  block:
    - name: Add apt key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add repository
      apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/code stable main"

    - name: Install package
      apt:
        name: code
  become: yes
